# Generated by Django 3.0.8 on 2020-07-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200712_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='market_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
