# Generated by Django 3.0.8 on 2020-07-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_market_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_of_animal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='animal_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
