# Generated by Django 3.0.8 on 2020-07-12 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200712_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='market_address',
        ),
        migrations.AddField(
            model_name='product',
            name='market_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.MarketAddByAdmin'),
        ),
    ]
