# Generated by Django 3.0.8 on 2020-07-15 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_commentreviewsstar'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category'),
        ),
    ]
