# Generated by Django 3.0.8 on 2020-07-15 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_remove_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='market_instance',
        ),
        migrations.CreateModel(
            name='ProductMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.MarketAddByAdmin')),
                ('product_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
