# Generated by Django 3.0.8 on 2020-07-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200716_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreviewsstar',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='commentreviewsstar',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
