# Generated by Django 3.0.8 on 2020-07-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200718_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_val', models.IntegerField(blank=True, max_length=10, null=True)),
                ('max_val', models.IntegerField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
