# Generated by Django 3.0.8 on 2020-07-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_pricefilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricefilter',
            name='max_val',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricefilter',
            name='min_val',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
