# Generated by Django 3.0.8 on 2020-07-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20200718_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricefilter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
