# Generated by Django 3.0.8 on 2020-07-30 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedanimallivestock',
            name='cost_of_animal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addedanimallivestock',
            name='date_of_purchase',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addedanimallivestock',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True),
        ),
    ]
