# Generated by Django 3.0.8 on 2020-07-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofileinfo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
