# Generated by Django 3.0.8 on 2020-07-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200730_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentschild',
            name='child_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
