# Generated by Django 3.0.8 on 2020-07-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_addedanimallivestock_allgalleryaddedbyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedanimallivestock',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=1000, null=True),
        ),
    ]
