# Generated by Django 3.0.8 on 2020-07-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_descriptiontable_heathinformation_milklitre'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedanimallivestock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
